theme: jekyll-theme-minimal
title: ''
description: 
  <ul>
  <li><a href="/chatgpt_manual">Главная</a></li>
  <li><a href="/chatgpt_manual/pages/СhatGPT_usage">Как пользоваться ChatGPT</a></li>
  <li><a href="/chatgpt_manual/pages/СhatGPT_IT_usage">Советы по использованию ChatGPT в IT</a></li>
  <li><a href="/chatgpt_manual/pages/СhatGPT_registration">Как зарегистрироваться в ChatGPT?</a></li>
  <li><a href="/chatgpt_manual/pages/future_of_СhatGPT">Мысли про будущее ChatGPT и нейросетей</a></li>
  </ul>
logo: "images/СhatGPT_Инструкция_по_применению.png"
layout: post
markdown: kramdown