theme: jekyll-theme-minimal
title: chatGPT. Инструкция по применению
description: 
  Как использовать chatGPT? Чтобы сэкономить себе время на работе и в личной жизни?
  <br>
  <ul>
  <li><a href="https://rogozinushka.github.io/chatgpt_manual/pages/Общие%20сценарии%20использования.md">Общие сценарии использования</a></li>
  <li>Как можно использовать chatGPT в IT. WIP</li>
  <li>Как зарегистрироваться в chatGPT? WIP</li>
  <li>chatGPT нас заменит? Мысли про будущее chatGPT. WIP</li>
  </ul>
logo: "/images/chatGPT_Инструкция_по_применению.png"
layout: post