theme: jekyll-theme-minimal
title: ''
description: 
  <ul>
  <li><a href="/chatgpt_manual">Главная</a></li>
  <li><a href="/chatgpt_manual/pages/ChatGPT_usage">Как пользоваться ChatGPT</a></li>
  <li><a href="/chatgpt_manual/pages/ChatGPT_IT_usage">Советы по использованию ChatGPT в IT</a></li>
  <li><a href="/chatgpt_manual/pages/ChatGPT_registration">Как зарегистрироваться в ChatGPT?</a></li>
  <li><a href="/chatgpt_manual/pages/future_of_ChatGPT">Мысли про будущее ChatGPT и нейросетей</a></li>
  <li><a href="/chatgpt_manual/pages/feedback">Обратная связь</a></li>
  </ul>
logo: "images/ChatGPT_Инструкция_по_применению.png"
layout: post
markdown: kramdown