theme: jekyll-theme-minimal
title: chatGPT. Инструкция по применению
description: 
  <ul>
  <li><a href="https://rogozinushka.github.io/chatgpt_manual/">Главная</a></li>
  <li><a href="https://rogozinushka.github.io/chatgpt_manual/pages/Как пользоваться chatGPT">Как пользоваться chatGPT</a></li>
  <li>Как можно использовать chatGPT в IT</li>
  <li>Как зарегистрироваться в chatGPT?</li>
  <li>chatGPT нас заменит?</li>
  </ul>
logo: "/images/chatGPT_Инструкция_по_применению.png"
layout: post