theme: jekyll-theme-minimal
title: chatGPT. Инструкция по применению
description: 
  Как использовать chatGPT? Чтобы сэкономить себе время на работе и в личной жизни?
  <br><br>  
  <a href="https://github.com/rogozinushka/chatgpt_manual/pages/Общие сценарии использования.md">Общие сценарии использования</a>   
  <br><br>
  Как можно использовать chatGPT в IT. WIP
  <br><br>
  Как зарегистрироваться в chatGPT? WIP
  <br><br>
  chatGPT нас заменит? Мысли про будущее chatGPT. WIP
logo: "/images/chatGPT_Инструкция_по_применению.png"
