theme: jekyll-theme-minimal
title: ''
description: 
  <ul>
  <li><a href="/chatgpt_manual">Главная</a></li>
  <li><a href="/chatgpt_manual/pages/ChatGPT_usage">Как пользоваться ChatGPT</a></li>
  <li><a href="/chatgpt_manual/pages/ChatGPT_IT_usage">Советы по использованию ChatGPT в IT</a></li>
  <li><a href="/chatgpt_manual/pages/ChatGPT_registration">Как зарегистрироваться в ChatGPT?</a></li>
  <li><a href="/chatgpt_manual/pages/future_of_ChatGPT">ChatGPT и безработица - что нас ждет в будущем?</a></li>
  <li><a href="/chatgpt_manual/pages/ChatGPT_makes_us_stupid">ChatGPT - убийца интеллекта человека?</a></li>
  <li><a href="/chatgpt_manual/pages/feedback">Обратная связь</a></li>
  </ul>
logo: "images/ChatGPT_Инструкция_по_применению.png"
layout: post
markdown: kramdown